---
title: "Homework4"
author: "Sri Seshadri"
date: "August 19, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source('C:/Users/sujat/Desktop/MSDS460/estimatepi.R')
```

```{r}
library(purrr)
library(ggplot2)
N <- seq(1000,10000,500)
set.seed(111)
results <- map_df(.x = N,.f = estimatepi) %>% 
  mutate(N = N)
```

```{r}
# Plot results

results %>% 
  ggplot(mapping = aes(x = N, y = pi_estimate,ymin = LowerConfLimit,ymax = UpperConfLimit)) + 
  geom_pointrange(alpha = 0.5) + geom_hline(yintercept = pi, col = 'red') + 
  geom_hline(yintercept = pi-0.05, lty = 2, col = 'red') +
  geom_hline(yintercept = pi+0.05, lty = 2, col = 'red') +
  geom_vline(xintercept = 7750, col = 'blue') +
  theme_bw()

```

```{r}
N_optimal = rep(8000,500)

# 500 simulation iterations
results_rep <- map_df(.x = N_optimal,.f = estimatepi)
lattice::histogram(x = ~pi_estimate, data = results_rep)


```

```{r}
knitr::kable(data.frame(Pi_std.Dev = sd(results_rep$pi_estimate),
           pi_stdError = results$pi_StdError[results$N == 8000],
           PercentWithinCI = length(between(results_rep$pi_estimate,results$LowerConfLimit[results$N == 8000],
                                            results$UpperConfLimit[results$N == 8000]))/500*100))
```

